/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedTodosIndexRouteImport } from './routes/_authed/todos/index'
import { Route as AuthedTodosNewRouteImport } from './routes/_authed/todos/new'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTodosIndexRoute = AuthedTodosIndexRouteImport.update({
  id: '/todos/',
  path: '/todos/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTodosNewRoute = AuthedTodosNewRouteImport.update({
  id: '/todos/new',
  path: '/todos/new',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/todos/new': typeof AuthedTodosNewRoute
  '/todos/': typeof AuthedTodosIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthedIndexRoute
  '/todos/new': typeof AuthedTodosNewRoute
  '/todos': typeof AuthedTodosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/todos/new': typeof AuthedTodosNewRoute
  '/_authed/todos/': typeof AuthedTodosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/todos/new' | '/todos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/todos/new' | '/todos'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/'
    | '/_authed/todos/new'
    | '/_authed/todos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/todos/': {
      id: '/_authed/todos/'
      path: '/todos'
      fullPath: '/todos/'
      preLoaderRoute: typeof AuthedTodosIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/todos/new': {
      id: '/_authed/todos/new'
      path: '/todos/new'
      fullPath: '/todos/new'
      preLoaderRoute: typeof AuthedTodosNewRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedTodosNewRoute: typeof AuthedTodosNewRoute
  AuthedTodosIndexRoute: typeof AuthedTodosIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedTodosNewRoute: AuthedTodosNewRoute,
  AuthedTodosIndexRoute: AuthedTodosIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
